version: '3.8'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: event_member_management
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data

  api:
    image: ghcr.io/codeseoul/event_member_management_backend:latest
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: manager
      DATABASE_PASSWORD: devpassword
      spring_profiles_active: local
    ports:
      - target: 8080
        published: 8000
    depends_on:
      - database
    restart: on-failure

volumes:
  data:
