version: "3.8"

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Normally, you'd want to setup a volume for the data storage
      # We want to easily clean up the data from this container, so
      # we won't persist it beyond the lifetime of the container
      # via a volume.
      # The below bind mount will run all of the SQL files in
      # migrations/up on start. We will later replace this with
      # a proper migration system that we can use in both prod/dev.
      - type: bind
        source: ./migrations/up
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  dev:
    image: node:lts-alpine
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    environment:
      DB_HOST: database
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command:
      - npm
      - run
      - start:dev
