version: "3.8"

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  dev:
    image: node:lts-alpine
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    environment:
      DB_HOST: database
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command:
      - npm
      - run
      - start:dev
